name: linter

on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  make-lint:
    # Name the Job
    name: Runs linter
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      # https://github.com/actions/checkout
    - name: Checkout code
      uses: actions/checkout@v2

      # installing dependencies
    - name: Install Dependencies
      # Install project
      run: make install

      # Runs the Linter action
    - name: Run linter
      run: make lint
